### ISSUE TITLE
Support for enabling and configuring PgBouncer in azurerm_postgresql_flexible_server resource

### ISSUE THREAD

**Issue by ruiskander** [hashicorp/terraform-provider-azurerm#13479]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enabling and configuring PgBouncer in Azure Database for PostgreSQL - Flexible Server
https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-pgbouncer

### New or Affected Resource(s)

* azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server" "example" {
  name                   = "example-psqlflexibleserver"
  resource_group_name    = azurerm_resource_group.example.name
  location               = azurerm_resource_group.example.location
  version                = "12"
  delegated_subnet_id    = azurerm_subnet.example.id
  private_dns_zone_id    = azurerm_private_dns_zone.example.id
  administrator_login    = "psqladminun"
  administrator_password = "H@Sh1CoR3!"
  storage_mb = 32768
  sku_name   = "GP_Standard_D4s_v3"

  pgbouncer {
    enabled                   = true
    default_pool_size         = 40
    max_client_conn           = 400
    pool_mode                 = "TRANSACTION"
    min_pool_size             = 0
    ignore_startup_parameters = ["extra_float_digits",]
    query_wait_timeout        = 120
    stats_users               = "user name"
  }
}
```

### References

* #0000

**Comment by dploeger** [comment]
This is already possible using `azurerm_postgresql_flexible_server_configuration`:

```
resource "azurerm_postgresql_flexible_server_configuration" "pgbouncer" {
  name      = "pgbouncer.enabled"
  value     = "true"
  server_id = azurerm_postgresql_flexible_server.server.id
}

```

**Comment by lra** [comment]
@dploeger We tried and this leads to the AZ API sending terraform 500 errors, which render the whole state unusable as the API keep replying 500s to setting that terraform was unable to apply.
This seem to be due to an ordering problem (one pgbouncer setting has to be enabled and apply before the others) which is hard to express using terraform, unless specifying "depend_on" between different configuration settings.

**Comment by dploeger** [comment]
Oh? Strange. It worked flawless here.

**Comment by command0r** [comment]
This is the config you add to configure pgBouncer (as an addition to a code published by the author):
`## Postgres SQL flexible server - pgBouncer configuration
locals {
  pg_config = {
    "pgbouncer.enabled"                   : "true",
    "pgbouncer.default_pool_size"         : "50"
    "pgBouncer.max_client_conn"           : "5000",
    "pgBouncer.pool_mode"                 : "TRANSACTION",
    "pgBouncer.min_pool_size"             : "0",
    "pgbouncer.query_wait_timeout"        : "120s"
  }
}

resource "azurerm_postgresql_flexible_server_configuration" "postgres_fs_config" {
  for_each = local.pg_config
  name = each.key
  value = each.value
  server_id = azurerm_postgresql_flexible_server.example.id
}`

You may not need the last 5 parameters if you stick to a standard configuration, so the solution @dploeger published originally should work like a charm.

**Comment by smitaqueries** [comment]
> @dploeger We tried and this leads to the AZ API sending terraform 500 errors, which render the whole state unusable as the API keep replying 500s to configuration settings that terraform thought it applied but was unable to apply. This seem to be due to an ordering problem (one pgbouncer setting has to be enabled and applied before the others) which is hard to express using terraform, unless specifying "depend_on" between different configuration settings.

What is the solution to this

**Comment by ridicolos** [comment]
I currently have the same error as @lra.

There seems to be some problem with the ordering of the `server_configurations`.
The example code suggested by @command0r doesn't work on my end.


For now I fixed this with the following:

## main.tf

```terraform
resource "azurerm_postgresql_flexible_server_configuration" "db-config" {
  for_each  = local.pg_config
  name      = each.key
  value     = each.value
  server_id = azurerm_postgresql_flexible_server.db.id
}

# This has to be separated because of https://github.com/hashicorp/terraform-provider-azurerm/issues/13479
resource "azurerm_postgresql_flexible_server_configuration" "db-pgbouncer-config" {
  for_each   = local.pgbouncer_config
  name       = each.key
  value      = each.value
  server_id  = azurerm_postgresql_flexible_server.db.id
  depends_on = [azurerm_postgresql_flexible_server_configuration.db-config]
}
```

## local.tf

```terraform
  pg_config = {
    "azure.extensions" : "POSTGIS,CITEXT,PG_STAT_STATEMENTS"
    "azure.accepted_password_auth_method" : "SCRAM-SHA-256"
    "pgbouncer.enabled" : "true"
  }
  pgbouncer_config = {
    "pgbouncer.default_pool_size" : "50"
    "pgbouncer.ignore_startup_parameters" : "extra_float_digits"
    "pgbouncer.max_client_conn" : "5000"
    "pgbouncer.min_pool_size" : "0"
    "pgbouncer.pool_mode" : "TRANSACTION"
    "pgbouncer.query_wait_timeout" : "120"
    "pgbouncer.server_idle_timeout" : "600"
  }
```

**Comment by rstra** [comment]
> Keep in mind that the pgbouncer configuration keys are not settable (at least the API returns an error) if pgbouncer is set to enabled = false.

@hypervtechnics - Will I be able to just depends_on for the other config keys to make sure that it is enabled? Or would I have to let 1 run fail, and then rerun an apply to set the configs?

**Comment by hypervtechnics** [comment]
You are able to use depends_on although you might get weird behaviour when switching the pgbouncer on or off.
Things I think of but did not test yet: Maybe use count with depends_on to fully delete pgbouncer related configuration resources when it is not enabled. Another option may include using the new azapi provider to fill that gap as it uses resource manager which does not have this weird behaviour in the described scenarios.

**Comment by holms** [comment]
anyone even noticed that `pgbouncer.client_tls_sslmode` param is gone? By default it was enforcing ssl which golang driver is not supporting..? Or maybe it's jus opensource software that I'm using it not supporting it.

**Comment by lieberlois** [comment]
Can't believe this is still an issue 😢  did any of you find a good solution for this? We currently conditionally switch into a Burstable SKU to save costs - but pgbouncer is not supported there. When we switch, then the pgbouncer server parameters cannot be set ... and not even queried ... so the apply fails even if you do `count = ... ? 1 : 0` etc.

**Comment by holms** [comment]
We actually moved to digital ocean because of this. I mean this is such a basic requirement that I even can't grasp how they don't care about this.

**Comment by philippeckelintive** [comment]
Working solution using [Azapi provider](https://registry.terraform.io/providers/Azure/azapi/latest):

```hcl
resource "azapi_update_resource" "pgbouncer_enabled" {
  type      = "Microsoft.DBforPostgreSQL/flexibleServers/configurations@2022-12-01"
  parent_id = azurerm_postgresql_flexible_server.example.id
  name      = "pgbouncer.enabled"
  body = jsonencode({
    properties = {
      value  = "true"
      source = "user-override"
    }
  })
}

resource "azapi_update_resource" "pgbouncer_default_pool_size" {
  depends_on = [azapi_update_resource.pgbouncer_enabled]
  type       = "Microsoft.DBforPostgreSQL/flexibleServers/configurations@2022-12-01"
  parent_id  = azurerm_postgresql_flexible_server.example.id
  name       = "pgbouncer.default_pool_size"
  body = jsonencode({
    properties = {
      value  = "40"
      source = "user-override"
    }
  })
}
```
