### ISSUE TITLE
Terraform azurerm_lb migration from 2.X to 3.X

### ISSUE THREAD

**Issue by AndreasMWalter** [hashicorp/terraform-provider-azurerm#16125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
`3.0.2`

### Affected Resource(s)

* `azurerm_lb`

### Expected Behaviour
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb#availability_zone
As mentioned in the `3.0.2` documentation it is expected that zonal deployments are the default configuration and therefore no replacement should be forced.

### Actual Behaviour
Provider wants to replace every load balancer that has a frontend ip configuration with AZs enabled, due to old default values being zonal deployment ["1","2","3"]
![image](https://user-images.githubusercontent.com/38529659/160600404-5949b368-305e-48f5-bbf3-d38e0e1299c2.png)

Setting the availability_zone parameter as mentioned in the documentation, does not work
![image](https://user-images.githubusercontent.com/38529659/160601139-5e14fe6e-d685-4c01-9dcc-3d2916e30b10.png)

Actual attribute name is `zone` not `availability_zone`  and only allowed config is list of strings ["1","2","3"]

Indicates unmentioned breaking change in azurerm_lb resource

### Steps to Reproduce

Create Loadbalancer with frontend ip configuration without `zone` attribute and any provider version `2.xx`.
Upgrade to provider 3.0.2.

1. `terraform apply`

### Important Factoids

Deployed to westeurope (which supports availability zones) 

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb#availability_zone

**Comment by AndreasMWalter** [comment]
azurerm_public_ip shows similar issue, default seems to have change but is not reflected in documentation
![image](https://user-images.githubusercontent.com/38529659/160609073-17536412-4838-49a7-afa5-fa26587246f6.png)

**Comment by AndreasMWalter** [comment]
Disregard my outcry, however documentation should still be updated to reflect the changes mentioned in:
I admit I search the changelogs for the given resource types and didn't see the message:

Resources supporting Availability Zones: Zones are now treated consistently across the Provider and the field within Terraform has been renamed to either zone (for a single Zone) or zones (where multiple can be defined) - the complete list of resources can be found in the 3.0 Upgrade Guide (https://github.com/hashicorp/terraform-provider-azurerm/issues/14588)

**Comment by sebader** [comment]
@AndreasMWalter I opened a doc fix PR https://github.com/hashicorp/terraform-provider-azurerm/pull/16209

**Comment by jeffw-test-wtbr** [comment]
I am also seeing an issue with an azurerm_lb frontend_ip_configuration and it seems that no matter what I do, terraform wants to recreate the lb.

Using `terraform state show`:
```
resource "azurerm_lb" "" {
    ...
    frontend_ip_configuration {
        ...
        zones = []
    }
}
```

When my config has no zones entry or the zones set to the empty array, I get this update:
```
          - zones                                              = [
              - "1",
              - "2",
              - "3",
            ] -> null # forces replacement
```

So, it would appear the config needs to be:
```
zones  = ["1", "2", "3"]
```

But alas:
```
          ~ zones                                              = [ # forces replacement
              + "1",
              + "2",
              + "3",
            ]
```

So I currently have no idea how I can configure this without terraform wanting to replace the load balancer.

**Comment by jeffw-test-wtbr** [comment]
Never mind, I was confusing 2 similarly named azurerm_lb's.

**Comment by tombuildsstuff** [comment]
Closing this out since the original issue has been fixed by #16209

**Comment by timwebster9** [comment]
I'm not sure how this is fixed.  I just ran into this, and I'm seeing this as well:

![image](https://user-images.githubusercontent.com/6548787/164204906-0591bd57-b32b-40e8-95d4-1ad28eb74566.png)

If that's not the correct attribute name, the docs still need fixing.  #16209 only changed the note section in the **public IP** resource page, not the attribute name or the note on the **load balancer** page.

So I'm still confused about:

- what is the correct value for availability zones here ('availability_zone' doesn't work): https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb#availability_zone
- what is the default behaviour?  Zone-redundant?  Zonal? No zone?

**Comment by tombuildsstuff** [comment]
@timwebster9 the Upgrade Guide contains details the changes: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide - see "Behavioural Updates" and "Resource: azurerm_lb" for the specifics

Agreed that this is a documentation issue still for LB however, I'll push a commit for that shortly - thanks for the heads up
