### ISSUE TITLE
New azurerm 3.21.0 error while parsing azurerm_log_analytics_solution

### ISSUE THREAD

**Issue by marcusfriede** [hashicorp/terraform-provider-azurerm#18235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_solution

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_solution" "serviceMap" {
  solution_name         = "ServiceMap"
  location              = azurerm_log_analytics_workspace.laWorkspace.location
  resource_group_name   = azurerm_log_analytics_workspace.laWorkspace.resource_group_name
  workspace_resource_id = azurerm_log_analytics_workspace.laWorkspace.id
  workspace_name        = azurerm_log_analytics_workspace.laWorkspace.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ServiceMap"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: parsing "/subscriptions/<ID>/resourcegroups/<RG>/providers/Microsoft.OperationsManagement/solutions/ServiceMap(<name>)": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

main.tf line 16, in resource "azurerm_log_analytics_solution" "serviceMap":
│   16: resource "azurerm_log_analytics_solution" "serviceMap" {
```

### Expected Behaviour

No error should appear

### Actual Behaviour

│ Error: parsing "/subscriptions/<ID>/resourcegroups/<RG>/providers/Microsoft.OperationsManagement/solutions/ServiceMap(<name>)": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

main.tf line 16, in resource "azurerm_log_analytics_solution" "serviceMap":
│   16: resource "azurerm_log_analytics_solution" "serviceMap" {

**Comment by swapnilpotnis** [comment]
Same is the case with DataExports

`parsing segment "staticDataExports": expected the segment "dataexports" to be "dataExports"`

**Comment by thomasriley** [comment]
We are also suffering from this issue and are pinning back to version 3.20.0 to workaround this for now.

**Comment by liuwuliuyun** [comment]
I have tested locally with following config files and works in 3.21.1, could you try again with the latest version of provider?

`provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "yunliu-test2"
  location = "east us"
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "yunliu-test2"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
}

resource "azurerm_log_analytics_solution" "serviceMap" {
  solution_name         = "ServiceMap"
  location              = azurerm_log_analytics_workspace.test.location
  resource_group_name   = azurerm_log_analytics_workspace.test.resource_group_name
  workspace_resource_id = azurerm_log_analytics_workspace.test.id
  workspace_name        = azurerm_log_analytics_workspace.test.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ServiceMap"
  }
}`

Besides, could you help to provide when did this error appear? For example, is it in when you creating the resource or is it when you updating the resource?

**Comment by liuwuliuyun** [comment]
Here is the output when I run "terraform apply" with above config.

Plan: 3 to add, 0 to change, 0 to destroy.
azurerm_resource_group.test: Creating...
azurerm_resource_group.test: Creation complete after 6s [id=/subscriptions/*****/resourceGroups/yunliu-test2]
azurerm_log_analytics_workspace.test: Creating...
azurerm_log_analytics_workspace.test: Still creating... [10s elapsed]
azurerm_log_analytics_workspace.test: Creation complete after 16s [id=/subscriptions/*****/resourceGroups/yunliu-test2/providers/Microsoft.OperationalInsights/workspaces/yunliu-test2]
azurerm_log_analytics_solution.serviceMap: Creating...
azurerm_log_analytics_solution.serviceMap: Creation complete after 6s [id=/subscriptions/*****/resourceGroups/yunliu-test2/providers/Microsoft.OperationsManagement/solutions/ServiceMap(yunliu-test2)]

**Comment by liuwuliuyun** [comment]
> Same is the case with DataExports
> 
> `parsing segment "staticDataExports": expected the segment "dataexports" to be "dataExports"`

Hi, could you help to test if your config works with the latest provider version or specify the property not working with resource name? I have tested following config with provider version 3.21.1 and it works fine.

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "yunliutest22"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "exampleworkspaceyunliu"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_storage_account" "example" {
  name                     = "examplestoraccyunliu"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_log_analytics_data_export_rule" "example" {
  name                    = "dataExport1"
  resource_group_name     = azurerm_resource_group.example.name
  workspace_resource_id   = azurerm_log_analytics_workspace.example.id
  destination_resource_id = azurerm_storage_account.example.id
  table_names             = ["Heartbeat"]
  enabled                 = true
}

**Comment by grillba** [comment]
Seems somewhat related to #18244

**Comment by marcusfriede** [comment]
The error
`"parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups""`
is still present in azurerm provider v3.21.1

**Comment by liuwuliuyun** [comment]
> Seems somewhat related to #18244

Agreed, I thinks this issue is actually described in 18244.

**Comment by jan-hudec** [comment]
Not sure whether it's exactly the same issue, but I am seeing the same error when trying to import an `azurerm_log_analytics_workspace` (created manually, trying to switch to terraform). Tried with 3.19.1, 3.20.0 and 3.21.1, no difference.

**Comment by J0F3** [comment]
Same for `azurerm_monitor_diagnostic_setting` starting with azurerm version 3.21.

Azure Resource IDs are and were never case sensitive. So why does the azurerm provider care now, after a minor update (which should not included breaking changes), suddenly about the casing of Azure Resource IDs? What is the idea here?

**Comment by grillba** [comment]
I have also tested by changing the case of the resource ID and running an apply but the case is ignored and there is no change to the resource.

**Comment by J0F3** [comment]
@tombuildsstuff Any updates? What's happening now? 
arzurerm from version 3.21 onwards is unusable for us now (had to rollback to version 3.20) until there is a fix or some information how to workaround the error. 
So any information or updates would be much apricated. Thx!

**Comment by Amier3** [comment]
@J0F3 We just opened https://github.com/hashicorp/terraform-provider-azurerm/pull/18291 to fix this. As tom noted in #18244 , we needed to perform a state migration to reconcile the new API requirements. 

For some context, this issue and a couple others popped up after we upgraded our SDK to the newer version of Azure's log analytics API ( [this](https://github.com/hashicorp/terraform-provider-azurerm/pull/18098) is the original PR and we fixed a similar issue that arose from it in[ 3.21.1](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3211-september-02-2022) ). 

Tom gives a good overview in https://github.com/hashicorp/terraform-provider-azurerm/issues/5455 that gives some insight into why bugs like this tend to pop up after upgrades:

> Whilst the Azure API Specification states that Resource ID's are Case Insensitive - in practice across many API's they're not - which is a frequent source of subtle bugs. This means that we're forced to treat Resource ID's (and thus the components which comprise them) as case-sensitive unfortunately this behaviour is intentional


So this issue would be one of those subtle bugs. We try to be careful with when/how we upgrade different API specs  to balance the need to stay up to date with Azure features while maintaining provider stability, but sometimes certain bugs will slip through the crack. We would like to eventually come around and fix this problem holistically instead of on a case-by-case basis, but I wouldn't be able to give any timetable on when that'd be.

**Comment by Sander-IctQ** [comment]
At the moment I am using v3.22 and with newly created resource I still get the following message:

`Error: Reading Security Center Log Analytics Workspace ID: parsing "/subscriptions/XXXXXX/resourcegroups/XXXXXX/providers/microsoft.operationalinsights/workspaces/mdc-security-workspace": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"`

resourcegroups and microsoft.operationalinsights still are not correct.
