### ISSUE TITLE
Terraform azurerm provider version 3.50.0 has compatibility or some missing parameter issues for azurerm_application_gateway resource

### ISSUE THREAD

**Issue by kbzacher** [hashicorp/terraform-provider-azurerm#21453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

>= 1.1.3

### AzureRM Provider Version

>=2.91.0

### Affected Resource(s)/Data Source(s)

module.app_gateway.azurerm_application_gateway.app_gat

### Terraform Configuration Files

```hcl
resource "random_string" "rnd" {
  length  = 3
  lower   = true
  number  = true
  upper   = false
  special = false
}

locals {
  agwName        = "${substr("app-gw-${var.name}-${var.environment}", 0, 76)}-${random_string.rnd.result}"
  root_cert_name = "ericsson-root"
}


resource "azurerm_public_ip" "pip_app_gw" {
  name                = "pip-fe-${local.agwName}"
  resource_group_name = var.resource_group_name
  location            = var.location
  allocation_method   = "Static"
  domain_name_label   = "dns-ericsson-eca-${var.location}-${var.environment}"
  sku                 = "Standard"
  zones               = var.location != "uaenorth" ? tolist(["1","2","3"]) : null

  tags = merge(var.tags_always_present, var.tags)
}

module "pipDiagnostics" {
  count                   = var.enable_logging ? 1 : 0
  source                  = "../diagnosticSettings"
  targetResourceId        = azurerm_public_ip.pip_app_gw.id
  workspaceId             = var.workspaceId
  logs_storage_account_id = var.logs_storage_account_id
}

resource "azurerm_application_gateway" "app_gateway" {
  name                = local.agwName
  resource_group_name = var.resource_group_name
  location            = var.location
  enable_http2        = true
  firewall_policy_id  = azurerm_web_application_firewall_policy.gateway_policy.id

  sku {
    name = "WAF_v2"
    tier = "WAF_v2"
  }

  custom_error_configuration {
    status_code           = "HttpStatus502"
    custom_error_page_url = "${var.public_content_endpoint}/custom-error-pages/HttpStatus502.html"  // hard codded    url should be passed                      
  }

  autoscale_configuration {
    min_capacity = 2
    max_capacity = 10
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [var.managed_identity]
  }

  # Custom Cipher Suites For Azure App Gateway
  ssl_policy {
    min_protocol_version = "TLSv1_2"
    policy_type          = "Custom"
    cipher_suites = [
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    ]
  }

  gateway_ip_configuration {
    name      = "ipconfig-gw-${local.agwName}"
    subnet_id = var.subnet_id
  }

  frontend_port {
    name = "httpsPort"
    port = 443
  }

  frontend_ip_configuration {
    name                 = "ipconfig-fe-${local.agwName}"
    public_ip_address_id = azurerm_public_ip.pip_app_gw.id
  }

  backend_address_pool {
    name = "be-pool-${local.agwName}"
  }

  backend_http_settings {
    name                  = "be-https-${local.agwName}"
    cookie_based_affinity = "Disabled"
    port                  = 443
    protocol              = "Https"
    request_timeout       = 1
  }

  http_listener {
    name                           = "listener-https-${local.agwName}"
    frontend_ip_configuration_name = "ipconfig-fe-${local.agwName}"
    frontend_port_name             = "httpsPort"
    protocol                       = "Https"
    ssl_certificate_name           = var.certificate_name
  }

  request_routing_rule {
    name                       = "rr-https-${local.agwName}"
    rule_type                  = "Basic"
    http_listener_name         = "listener-https-${local.agwName}"
    backend_address_pool_name  = "be-pool-${local.agwName}"
    backend_http_settings_name = "be-https-${local.agwName}"
  }

  rewrite_rule_set {
    name = "add-custom-response-header"
    rewrite_rule {
      name = "XFrameHeaderRule"
      rule_sequence = 1
      response_header_configuration {
        header_name = "X-Frame-Options"
        header_value = "SAMEORIGIN"
      }
    }
  }

  ssl_certificate {
    name                = var.certificate_name
    key_vault_secret_id = replace(var.keyvault_certificateId, "/(${var.certificate_name}/.*)/", "${var.certificate_name}/")
  }

  trusted_root_certificate {
    name = local.root_cert_name
    data = file("${path.module}/${local.root_cert_name}.cer")
  }

  tags = merge(var.tags_always_present, var.tags)
  

  lifecycle {
    ignore_changes = [
      backend_address_pool,
      backend_http_settings,
      frontend_port,
      http_listener,
      probe,
      request_routing_rule,
      url_path_map,
      redirect_configuration,
      tags,
      // waf_configuration has to be ignored and disabled to avoid conflicts with WAF policy - https://github.com/Azure/azure-cli/issues/15520 
      // enabling waf_configuration would result in the gateway in a corrupt state that doesn't allow modifications by tge AGIC
      waf_configuration 
      
    ]
  }
}

module "appGwDiagnostics" {
  count                   = var.enable_logging ? 1 : 0
  source                  = "../diagnosticSettings"
  targetResourceId        = azurerm_application_gateway.app_gateway.id
  workspaceId             = var.workspaceId
  logs_storage_account_id = var.logs_storage_account_id
}

resource "azurerm_web_application_firewall_policy" "gateway_policy" {
  name                = "wafpolicy-${local.agwName}"
  resource_group_name = var.resource_group_name
  location            = var.location

  custom_rules {
    name      = "IdmanNmapRestriction"
    priority  = 2
    rule_type = "MatchRule"

    match_conditions {
      match_variables {
        variable_name = "RemoteAddr"
      }

      operator           = "IPMatch"
      negation_condition = true
      match_values       = [ "18.209.215.159", "54.243.186.70"]
    }

    match_conditions {
      match_variables {
        variable_name = "RequestUri"
      }

      operator           = "BeginsWith"
      negation_condition = false
      match_values       = ["/status", "/network-map", "/api/v1/health", "/api/health"]
      transforms         = ["Lowercase"]
    }
    action = "Block"
  }

  policy_settings {
    enabled                     = true
    mode                        = "Prevention"
    request_body_check          = true
    file_upload_limit_in_mb     = 1000
    max_request_body_size_in_kb = 1024
  }

  managed_rules {
    exclusion {
      match_variable          = "RequestHeaderNames"
      selector_match_operator = "Contains"
      selector                = "/api/commondownloadFile"
    }

    exclusion {
      match_variable          = "RequestHeaderNames"
      selector_match_operator = "Contains"
      selector                = "/api/addFilesToContainer"
    }

    exclusion {
      match_variable          = "RequestHeaderNames"
      selector_match_operator = "Contains"
      selector                = "/api/v1/evidences/file"
    }

    exclusion {
      match_variable          = "RequestArgNames"
      selector_match_operator = "Equals"
      selector                = "fileName"
    }

    exclusion {
      match_variable          = "RequestArgNames"
      selector_match_operator = "Equals"
      selector                = "fileStoragePath"
    }

    exclusion {
      match_variable          = "RequestArgNames"
      selector_match_operator = "Equals"
      selector                = "fileUrl"
    }

    exclusion {
      match_variable          = "RequestArgNames"
      selector_match_operator = "Equals"
      selector                = "sdeReport"
    }

    exclusion {
      match_variable          = "RequestArgNames"
      selector_match_operator = "Contains"
      selector                = "description"
    }

    exclusion {
      match_variable          = "RequestArgNames"
      selector_match_operator = "Equals"
      selector                = "extendedAttributes.attributeValue"
    }

    managed_rule_set {
      type    = "OWASP"
      version = "3.2"
      rule_group_override {
        rule_group_name = "REQUEST-942-APPLICATION-ATTACK-SQLI"
        disabled_rules = [
          "942200",
          "942260",
          "942370",
          "942430",
          "942300",
          "942340",
          "942440",
          "942450" # auth callbacks contains HEX that which is being blocked by this rule
        ]
      }
      rule_group_override {
        rule_group_name = "REQUEST-920-PROTOCOL-ENFORCEMENT"
        disabled_rules = [
          "920230"
        ]
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: ID was missing the `firewallPolicies` element
│
│ with module.app_gateway.azurerm_application_gateway.app_gateway,
│ on ../modules/app_gateway/main.tf line 40, in resource "azurerm_application_gateway" "app_gateway":
│ 40: firewall_policy_id = azurerm_web_application_firewall_policy.gateway_policy.id
│
╵
```

### Expected Behaviour

The Terraform code fails sometimes whether we use the latest azure version and it works sometimes.

### Steps to Reproduce

It keeps fails on Terraform plan

**Comment by tombuildsstuff** [comment]
hi @kbzacher 

Thanks for opening this issue.

There's multiple versions of the Azure Provider mentioned in this bug report (`v3.50.0` and `v2.91.0`) - however I believe bug in `v3.50.0` (where the incorrect validation function was used) has been fixed in the latest version of the Provider, can you try upgrading to `v3.52.0` and see if that works for you?

Since I believe this has been fixed in the latest version of the Provider I'm going to close this issue for the moment, but should this still be an issue in the latest version of the Provider then please let us know and we'll take another look.

Thanks!

**Comment by kbzacher** [comment]
Hi @tombuildsstuff .
It still does not work with latest version of Azure provider . 
![967e5cf4-bb06-4e23-82a8-f4c7d68aa8f7](https://user-images.githubusercontent.com/113425582/232806215-45fa9c9a-3b18-496a-9564-a13a3ca640e3.jpg)

**Comment by tombuildsstuff** [comment]
@kbzacher that error message states that the Provider Versions required via the `required_providers` or `provider` block aren't resolvable (there's a requirement for `=2.91.0`, and `>=3.34.0` and `< 3.50.0` and `=3.52.0`) - so you'll need to address that in your Terraform Configuration to be able to use the newer provider version, this is unrelated to the fix above.
