### ISSUE TITLE
azure app service plan support for P0V3

### ISSUE THREAD

**Issue by filipg04** [hashicorp/terraform-provider-azurerm#21554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.53.0

### Affected Resource(s)/Data Source(s)

azurerm_service_planv

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "asp" {
  name                = "name"
  location            = "West Europe"
  resource_group_name = "test"
  tags                = []
  os_type             = "Linux"
  sku_name            = P0v3
  worker_count        = 1 
}
```

### Debug Output/Panic Output

```shell
expected sku_name to be one of [B1 B2 B3 S1 S2 S3 P1v2 P2v2 P3v2 P1v3 P2v3 P3v3 Y1 EP1 EP2 EP3 F1 I1 I2 I3 I1v2 I2v2 I3v2 D1 SHARED WS1 WS2 WS3], got P0v3
```

### Expected Behaviour

to have an app service plan corresponding the new supported plan

### Actual Behaviour

error

### Steps to Reproduce

terraform plan failed

### Important Factoids

no

**Comment by kasattejaswi** [comment]
Just an heads up, I am working on the fix of this issue.

**Comment by troyha** [comment]
Any ETA on this fix please?

**Comment by bubbletroubles** [comment]
I believe this was fixed in provider version 3.52 as per this commit - https://github.com/hashicorp/terraform-provider-azurerm/commit/a5dfcfa189126a3f633bc073290c052f820998ef

I've just tested with the following config and it works fine
```
resource "azurerm_service_plan" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "P0v3"
}
```

However the docs don't reflect this is a valid SKU. PR #21966 has been raised to address.

**Comment by bubbletroubles** [comment]
Also in the original issue, the sku_name does not have quotes around it. That may be the cause of the issue.

resource "azurerm_service_plan" "asp" {
  name                = "name"
  location            = "West Europe"
  resource_group_name = "test"
  tags                = []
  os_type             = "Linux"
  **sku_name            = P0v3**
  worker_count        = 1 
}

**Comment by aristosvo** [comment]
What a colleague of mine noticed was that in the GUI `P0v3` doesn't show as an option when doing an upgrade from `P1v2`, even when in a region which shows in `az appservice list-locations --sku P0V3 -o tsv`.

I'm currently unaware why this is the case, but this might be the same reason why upgrades fail.

**Comment by 4865783a5d** [comment]
@aristosvo The resource group containing the app service plan needs to be eligible for the new workloads. If you've created the resource group a while ago, P0V3 won't be supported. It is documented here: https://learn.microsoft.com/en-us/azure/app-service/app-service-configure-premium-tier#scale-up-from-an-unsupported-resource-group-and-region-combination

**Comment by troyha** [comment]
@mbfrahry @4865783a5d This is still an issue for me: "expected sku_name to be one of [B1 B2 B3 S1 S2 S3 P1v2 P2v2 P3v2 P1v3 P2v3 P3v3 Y1 EP1 EP2 EP3 F1 I1 I2 I3 I1v2 I2v2 I3v2 D1 SHARED WS1 WS2 WS3], got P0v3" is the error.

It builds and deploys correctly when using P1v3. I can manually modify the app plan to P0v3 through the portal so it is not the RG or plan that is the issue. What additional information do you need from me to help troubleshoot the issue?

**Comment by bubbletroubles** [comment]
@troyha  which region are you deploying to?

**Comment by troyha** [comment]
> @troyha which region are you deploying to?

Australia East
