### ISSUE TITLE
Inconsistencies in casing for azurerm_management_group_policy_assignment

### ISSUE THREAD

**Issue by BrianPickering-Cigna** [hashicorp/terraform-provider-azurerm#23519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.0

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group_policy_assignment

### Terraform Configuration Files

```hcl
provider "azurerm" {
  skip_provider_registration = true
  features {}
}

data "azurerm_management_group" "mggeneralworkloadsdev" {
    name = "mggeneralworkloadsdev"
}

# /providers/microsoft.management/managementgroups/mggeneralworkloadsdev/providers/microsoft.authorization/policyassignments/
resource "azurerm_management_group_policy_assignment" "logicapp_governance" {
    name         = "logicapp_governance"
    display_name = "Logic App Governance"
    description  = "Assignment of the Logic App Governance initiative to management group."
    management_group_id = data.azurerm_management_group.mggeneralworkloadsdev.id

    metadata = <<METADATA
        {
            "category": "Custom"
        }
    METADATA

    policy_definition_id = "/providers/Microsoft.Management/managementGroups/mggeneralworkloadsdev/providers/Microsoft.Authorization/policysetdefinitions/logicapp_governance"
    parameters     = <<VALUE
    {
        "privateEndpointSubnetId": "",
        "privateDnsZoneId": "",
        "ContainerRegistriesShouldHaveRepositoryScopedAccessTokenDisabledEffect": "Deny",
        "ContainerRegistriesShouldNotAllowUnrestrictedNetworkAccessEffect": "Deny",
        "PublicNetworkAccessShouldbeDisabledForContainerRegistriesEffect": "Deny",
        "ContainerRegistriesShouldHaveLocalAdminAccountDisabledEffect": "Deny",
        "ConfigureContainerRegistriesWithPrivateEndpointsEffect": "Disabled",
        "ConfigureContainerRegistriesToUsePrivateDNSZonesEffect": "Disabled",
        "ContainerRegistriesShouldHaveExportsDisabledEffect": "Deny"
    }
    VALUE

    lifecycle {
        ignore_changes = []
    }
}
```

### Debug Output/Panic Output

```shell
None
```

### Expected Behaviour

Other AzureRM providers for Azure Policy (specifically, azurerm_policy_definition and azurerm_policy_set_definition) accept the provider IDs in a case-insensitive manner. This is important, because when importing resources, the Azure Portal returns IDs as all lowercase, while the AZ CLI tools provide/accept camelCase.

### Actual Behaviour

Copy/paste exact AssignmentIDs from Portal fail in import, and cause plans to replace Assignments, even when nothing has changed apart from the case of the AssignmentID. See attached images.

### Steps to Reproduce

Having difficulty adding images of failures. Will try attaching again after creating Issue.

Only the camelCase form succeeds for azurerm_management_group_policy_assignment, even though all-lower-case form works for azurerm_policy_definition and azurerm_policy_set_definition, and the all-lower-case form being a standard form presented by Portal.

**Comment by BrianPickering-Cigna** [comment]
Repeatedly getting "Something went really wrong, and we can't process that file." upon attempting to upload images. How can these be provided?

**Comment by BrianPickering-Cigna** [comment]
Second sample:
`PS C:\repos\Azure%20Policy%20-%20Consolidated\DeployPolicy\src-terraform-debug> terraform import 'azurerm_management_group_policy_assignment.logicapp_governance' '/providers/microsoft.management/managementGroups/mggeneralworkloadsdev/providers/microsoft.authorization/policyassignments/containerreg_governance'
data.azurerm_management_group.mggeneralworkloadsdev: Reading...
data.azurerm_management_group.mggeneralworkloadsdev: Read complete after 3s [id=/providers/Microsoft.Management/managementGroups/mggeneralworkloadsdev]
azurerm_management_group_policy_assignment.logicapp_governance: Importing from ID "/providers/microsoft.management/managementGroups/mggeneralworkloadsdev/providers/microsoft.authorization/policyassignments/containerreg_governance"...
╷
│ Error: ID was missing the `policyAssignments` element`

Again, the "policyassignments" element is present, all in lower-case, as provided by Copy/Paste from Portal.

**Comment by BrianPickering-Cigna** [comment]
Fourth sample:
`PS C:\repos\Azure%20Policy%20-%20Consolidated\DeployPolicy\src-terraform-debug> terraform import 'azurerm_management_group_policy_assignment.logicapp_governance' '/providers/microsoft.management/managementGroups/mggeneralworkloadsdev/providers/Microsoft.Authorization/policyAssignments/containerreg_governance'
data.azurerm_management_group.mggeneralworkloadsdev: Reading...
data.azurerm_management_group.mggeneralworkloadsdev: Read complete after 4s [id=/providers/Microsoft.Management/managementGroups/mggeneralworkloadsdev]
azurerm_management_group_policy_assignment.logicapp_governance: Importing from ID "/providers/microsoft.management/managementGroups/mggeneralworkloadsdev/providers/Microsoft.Authorization/policyAssignments/containerreg_governance"...
azurerm_management_group_policy_assignment.logicapp_governance: Import prepared!
  Prepared azurerm_management_group_policy_assignment for import
azurerm_management_group_policy_assignment.logicapp_governance: Refreshing state... [id=/providers/microsoft.management/managementGroups/mggeneralworkloadsdev/providers/Microsoft.Authorization/policyAssignments/containerreg_governance]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.`

Note that the Microsoft.Management provider is perfectly happy accepting microsoft.management.

**Comment by BrianPickering-Cigna** [comment]
Final sample: terraform plan results in the following output snippet:

`  # azurerm_management_group_policy_assignment.logicapp_governance must be replaced
-/+ resource "azurerm_management_group_policy_assignment" "logicapp_governance" {
      ~ id                   = "/providers/microsoft.management/managementGroups/mggeneralworkloadsdev/providers/Microsoft.Authorization/policyAssignments/logicapp_governance" -> (known after apply)
      ~ management_group_id  = "/providers/microsoft.management/managementGroups/mggeneralworkloadsdev" -> "/providers/Microsoft.Management/managementGroups/mggeneralworkloadsdev" # forces replacement
      ~ metadata             = jsonencode(
            {
              - createdBy = "dd7eff6d-fde1-4e6d-b0a4-c58271600cf2"
              - createdOn = "2022-11-14T19:49:31.6407223Z"
              - updatedBy = null
              - updatedOn = null
            }
        ) -> <<-EOT
            {
                        "category": "Custom"
                    }
        EOT
        name                 = "logicapp_governance"
      - not_scopes           = [] -> null
      ~ parameters           = jsonencode(
            {
              - LogicAppIntServiceEnvshouldbeencryptedwithcustomermanagedkeysEffect = {
                  - value = "Audit"
                }
              - LogicAppshouldbedeployedintoIntegrationServiceEnvironmentEffect     = {
                  - value = "Audit"
                }
              - ResourcelogsinLogicAppshouldbeenabledEffect                         = {
                  - value = "AuditIfNotExists"
                }
              - requiredRetentionDays                                               = {
                  - value = "365"
                }
            }
        ) -> <<-EOT
            {
                    "privateEndpointSubnetId": "",
                    "privateDnsZoneId": "",
                    "ContainerRegistriesShouldHaveRepositoryScopedAccessTokenDisabledEffect": "Deny",
                    "ContainerRegistriesShouldNotAllowUnrestrictedNetworkAccessEffect": "Deny",
                    "PublicNetworkAccessShouldbeDisabledForContainerRegistriesEffect": "Deny",
                    "ContainerRegistriesShouldHaveLocalAdminAccountDisabledEffect": "Deny",
                    "ConfigureContainerRegistriesWithPrivateEndpointsEffect": "Disabled",
                    "ConfigureContainerRegistriesToUsePrivateDNSZonesEffect": "Disabled",
                    "ContainerRegistriesShouldHaveExportsDisabledEffect": "Deny"
                }
        EOT
      ~ policy_definition_id = "/providers/Microsoft.Management/managementGroups/mggeneralworkloadsdev/providers/Microsoft.Authorization/policySetDefinitions/logicapp_governance" -> "/providers/Microsoft.Management/managementGroups/mggeneralworkloadsdev/providers/Microsoft.Authorization/policysetdefinitions/logicapp_governance" # forces replacement
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.`

Both the management group ID and policy definition IDs are unchanged, apart from case, but the provider is insisting on replacing the assignment.

Unfortunately, when the policy set is replaced, we lose all Exceptions which have been granted on that policy set, and have to recreate them.

**Comment by wuxu92** [comment]
Hi @BrianPickering-Cigna Thanks for filing this issue. The Terraform provider is designed as case-sensitive even some Azure APIs are insensitive. So we have to provide the right case of the `policy_definition_id` field (in the configuration), or add a [ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) argument for it.

**Comment by DevoOlga** [comment]
I have the same issue. Copied resource ID from azure portal, and it was funny logs:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/127196506/abb8d52a-7ed3-40b8-a83d-299cc7502d71)
it was reading scope, but still complaining. When I fixed cases, it  stated that resource is already managed by terraform.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @wuxu92‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
