### ISSUE TITLE
azurerm_pim_eligible_role_assignment waiting for Role Management Policy to become ready: couldn't find resource

### ISSUE THREAD

**Issue by ChrisTav424** [hashicorp/terraform-provider-azurerm#23775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.79.0

### Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
resource "time_static" "main" {}

resource "azurerm_pim_eligible_role_assignment" "main" {
      principal_id       = "8ed7898e-----"
      role_definition_id = "/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----"
      scope              = "/subscriptions/6918adf8----"

  schedule {
    start_date_time = time_static.main.rfc3339
expiration {
duration_days  = 365
            }
        }
    }
```

### Debug Output/Panic Output

```shell
Error: waiting for Role Management Policy: (Principal Id "ed681489----" / Scope "/subscriptions/6918adf8----" / Role Definition Id "/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----") to become ready: couldn't find resource (21 retries)
│ 
│   with module.pim["6918adf8----"].azurerm_pim_eligible_role_assignment.main,
│   on ..\..\..\..\tfmodules\pim\main.tf line 3, in resource "azurerm_pim_eligible_role_assignment" "main":
│    3: resource "azurerm_pim_eligible_role_assignment" "main" {
│ 
│ waiting for Role Management Policy: (Principal Id
│ "ed681489----" / Scope
│ "/subscriptions/6918adf8----" / Role Definition Id
│ "/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----")
│ to become ready: couldn't find resource (21 retries)
```

### Expected Behaviour

Apply successful

### Actual Behaviour

The apply fails with the 'waiting for Role Management Policy to become ready: couldn't find resource (21 retries)'

The PIM roles have been created in the portal and when I run another terraform plan / apply it states that the resource needs to be imported into state. 

This only seems to be a problem when you specify a scope at a subscription level

### Steps to Reproduce

terraform apply

### References

I have seen this referenced in a few places already but states that it is resolved

https://github.com/hashicorp/terraform-provider-azuread/issues/68
https://github.com/hashicorp/terraform-provider-azurerm/pull/22932

**Comment by smokedlinq** [comment]
Noticed this yesterday too. It might be an Azure issue, in the activity log we see the Started event but never a completed event. I think the team was going to open a case with MS as well, will report back if they find anything.

**Comment by ChrisTav424** [comment]
Thanks @smokedlinq I will raise this with them too

**Comment by jcframil** [comment]
I have been trying for a couple of days to make it work, and went through a couple of posts, just to find out this issue is marked as resolved. :smiling_face_with_tear: 

Also tried changing the scope to RG but it failed.

When I try to create the resource it fails as mentioned before. The import fails too, saying that cannot import a non-existent remote object . Curious thing that the `terraform apply` shows the resource ID that needs to be imported :thinking: 

That's unusable for us at the moment.

### Terraform Version
1.5.7

### AzureRM Provider Version
3.79.0
3.70.0
3.65.0

### Output after `terraform apply`

```terraform
Error: A resource with the ID "/subscriptions/---/---/---/xxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_pim_eligible_role_assignment" for more information.
 
   with azurerm_pim_eligible_role_assignment.test,
   on elegible.tf line 15, in resource "azurerm_pim_eligible_role_assignment" "test":
   15: resource "azurerm_pim_eligible_role_assignment" "test" {
 
A resource with the ID "/subscriptions/---/---/---/xxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_pim_eligible_role_assignment" for more information.
```

### Output after `terraform import`

```terraform
Error: Cannot import non-existent remote object
 
 While attempting to import an existing object to
 "azurerm_pim_eligible_role_assignment.test", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
```

**Comment by MohnJadden** [comment]
> I have been trying for a couple of days to make it work, and went through a couple of posts, just to find out this issue is marked as resolved. 🥲
> 
> Also tried changing the scope to RG but it failed.
> 
> When I try to create the resource it fails as mentioned before. The import fails too, saying that cannot import a non-existent remote object . Curious thing that the `terraform apply` shows the resource ID that needs to be imported 🤔
> 
> That's unusable for us at the moment.
> 
> ### Terraform Versions
> 1.5.7 1.6.3
> 
> ### AzureRM Provider Versions
> 3.79.0 3.70.0 3.65.0
> 
> ### Output after `terraform apply`
> ```terraform
> Error: A resource with the ID "/subscriptions/---/---/---/xxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_pim_eligible_role_assignment" for more information.
>  
>    with azurerm_pim_eligible_role_assignment.test,
>    on elegible.tf line 15, in resource "azurerm_pim_eligible_role_assignment" "test":
>    15: resource "azurerm_pim_eligible_role_assignment" "test" {
>  
> A resource with the ID "/subscriptions/---/---/---/xxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_pim_eligible_role_assignment" for more information.
> ```
> 
> ### Output after `terraform import`
> ```terraform
> Error: Cannot import non-existent remote object
>  
>  While attempting to import an existing object to
>  "azurerm_pim_eligible_role_assignment.test", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
> ```

I had the same issue.  If you're using index keys and are working within Windows, you'd have to escape the index values [like so](https://github.com/hashicorp/terraform-provider-azurerm/issues/22678).  However, I ran into issues where the import claimed to be successful but didn't actually import into the state, so in the end I had to delete the existing PIM assignment from the portal and re-run it.

**Comment by xinfli** [comment]
Try change your role_definition_id to `/subscriptions/6918adf8----/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----`.

We had similar problem, but we are work with management group, it took us several days until we find what's wrong with it:
- If the scope is a management group, the role_definition_id should not contains scope, it should be like `/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----`
- If the scop is a subscription, scope is mandatory for role_definition_id: `/subscriptions/6918adf8----/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----`

Refer to section `Example Usage (Subscription)` and `Example Usage (Management Group)` in [document of azurerm_pim_eligible_role_assignment](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment)

**Comment by drdamour** [comment]
dupe of #23366

**Comment by TeamDman** [comment]
previously mentioned dupe is closed now, https://github.com/hashicorp/terraform-provider-azurerm/issues/23111 is open with active discussion (more about not-found errors than timeout tho)

**Comment by manicminer** [comment]
@ChrisTav424, @smokedlinq, @jcframil, @MohnJadden are you still experiencing this error with the latest provider (currently v3.104.2)?

**Comment by Scarlettliuyc** [comment]
hi @manicminer , I have customer still got same issue after update to azureRM 3.104.2
It still states that the Resource with ID XXX already exists - to be managed via Terraform this resource needs to be imported into the State 

Is it the case that the fix only works for PIM assignments created with the latest version of the provider and not pre-existing assignments?

**Comment by yashshah0809** [comment]
Hi @manicminer - i have been following this issue, was this issue only fixed in azurerm version >=  3.104.2? I ask cause i am still seeing this issue persist in 3.86.0

**Comment by manicminer** [comment]
@yashshah0809 Yes, this was ultimately resolved in v3.104 - you will need to upgrade your provider version if you are on v3.86

**Comment by manicminer** [comment]
@Scarlettliuyc Importing should work with PIM assignments created in earlier provider versions, as long as you first upgrade the provider version (and your state) to v3.104.2 or later.

**Comment by seankbeard** [comment]
@manicminer I'm having the issue on v3.113 when provisioning a new PIM role assignment
`Role Eligibility Schedule Request Name: "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx") to become found: context deadline exceeded`

The role creates in Azure and is usable, but Terraform does not receive the successful state

**Comment by jchryst-pack** [comment]
Still seeing the time out using v3.113.0. The assignment was created but the run fails.

`resource "azurerm_pim_eligible_role_assignment" "pim" {
  scope              = azurerm_resource_group.resource_group.id
  role_definition_id = "${azurerm_resource_group.resource_group.id}/providers/Microsoft.Authorization/roleDefinitions/8e3af6------"
  principal_id       = local.teams[var.team]
  schedule {
    expiration {
      duration_days = "365"
    }
  }
}`

Error: waiting for Scoped Role Eligibility Schedule Request (Scope: "/subscriptions/-----/resourceGroups/--"
│ Role Eligibility Schedule Request Name: "-------") to become found: context deadline exceeded
│ 
│   with module.rg.azurerm_pim_eligible_role_assignment.pim,
│   on .terraform/modules/rg/main.tf line 11, in resource "azurerm_pim_eligible_role_assignment" "pim":
│   11: resource "azurerm_pim_eligible_role_assignment" "pim" {
│ 
│ waiting for Scoped Role Eligibility Schedule Request (Scope: "/subscriptions/e-----/resourceGroups/-----"
│ Role Eligibility Schedule Request Name: "----") to become found: context deadline exceeded

**Comment by musekmkr** [comment]
> Try change your role_definition_id to `/subscriptions/6918adf8---/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----`.
> 
> We had similar problem, but we are work with management group, it took us several days until we find what's wrong with it:
> 
> * If the scope is a management group, the role_definition_id should not contains scope, it should be like `/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----`
> * If the scop is a subscription, scope is mandatory for role_definition_id: `/subscriptions/6918adf8----/providers/Microsoft.Authorization/roleDefinitions/ab8e14d6----`
> 
> Refer to section `Example Usage (Subscription)` and `Example Usage (Management Group)` in [document of azurerm_pim_eligible_role_assignment](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment)

This made all the difference and is included in the example in the terraform [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment#example-usage-subscription), so it seems to be a must.

`role_definition_id = "${data.azurerm_subscription.primary.id}${data.azurerm_role_definition.example.id}"`

Before adding the subscription ID to the role ID, terraform created the role assignment in Azure, but it took much longer than it should have and then failed saying the role assignment didn't exist.  After adding the sub ID, it created the assignment in seconds and terraform apply completed successfully. In my case, I was assigning a pim role to a Key Vault.

Without the subscription ID, I'm assuming it has to locate the subscription that contains the resource you are trying to assign the pim role to, which may explain why it takes so long to create the role assignment, especially if your tenant contains several subscriptions.  Just a theory...

**Comment by maartengo** [comment]
Curious, I did not get it working by explicitly adding the subscription id in the `role_definition_id`, but did get it working by setting the scope on the `azurerm_role_definition`:

```

data "azurerm_subscription" "current" {}
data "azurerm_role_definition" "contributor" {
  name = "Contributor"
  scope = data.azurerm_subscription.current.id
}
resource "time_static" "example" {}
resource "azurerm_pim_eligible_role_assignment" "assignment" {
  scope              = "${data.azurerm_subscription.current.id}/resourceGroups/rg-group/providers/Microsoft.KeyVault/vaults/kv"
  role_definition_id = data.azurerm_role_definition.contributor.id
  principal_id       = "dd279474----"

  schedule {
    start_date_time = time_static.example.rfc3339
    expiration {
      duration_days = 365
    }
  }
}
```

(for some reason the scope of the role id differed from my current subscription, but adding the scope there fixed it. it then automatically gets the `subscriptions/....` prefix)

**Comment by quilleo** [comment]
@maartengo That was exactly the hint I needed to solve the "context deadline" issue while creating a new azurerm_pim_eligible_role_assignment. In this case the scope was a subscription. I never would have thought to scope the role definition. Thanks!

**Comment by SPALLADI** [comment]
> Curious, I did not get it working (in 3.111.0) by explicitly adding the subscription id in the `role_definition_id`, but did get it working by setting the scope on the `azurerm_role_definition`:
> 
> ```
> 
> data "azurerm_subscription" "current" {}
> data "azurerm_role_definition" "contributor" {
>   name = "Contributor"
>   scope = data.azurerm_subscription.current.id
> }
> resource "time_static" "example" {}
> resource "azurerm_pim_eligible_role_assignment" "assignment" {
>   scope              = "${data.azurerm_subscription.current.id}/resourceGroups/rg-group/providers/Microsoft.KeyVault/vaults/kv"
>   role_definition_id = data.azurerm_role_definition.contributor.id
>   principal_id       = "dd279474----"
> 
>   schedule {
>     start_date_time = time_static.example.rfc3339
>     expiration {
>       duration_days = 365
>     }
>   }
> }
> ```
> 
> (for some reason the scope of the role id differed from my current subscription, but adding the scope there fixed it. it then automatically gets the `subscriptions/....` prefix)

Can I scope this at management group level?

**Comment by ChrisTav424** [comment]
> Curious, I did not get it working (in 3.111.0) by explicitly adding the subscription id in the `role_definition_id`, but did get it working by setting the scope on the `azurerm_role_definition`:
> 
> ```
> 
> data "azurerm_subscription" "current" {}
> data "azurerm_role_definition" "contributor" {
>   name = "Contributor"
>   scope = data.azurerm_subscription.current.id
> }
> resource "time_static" "example" {}
> resource "azurerm_pim_eligible_role_assignment" "assignment" {
>   scope              = "${data.azurerm_subscription.current.id}/resourceGroups/rg-group/providers/Microsoft.KeyVault/vaults/kv"
>   role_definition_id = data.azurerm_role_definition.contributor.id
>   principal_id       = "dd279474----"
> 
>   schedule {
>     start_date_time = time_static.example.rfc3339
>     expiration {
>       duration_days = 365
>     }
>   }
> }
> ```
> 
> (for some reason the scope of the role id differed from my current subscription, but adding the scope there fixed it. it then automatically gets the `subscriptions/....` prefix)

This worked for me too, thanks @maartengo. 

It looks like either I missed that in the docs or the docs have been updated so I will close this thread now

Thanks everyone
