### ISSUE TITLE
APIM Named Value Display Name unexpected validation error 

### ISSUE THREAD

**Issue by alexwiese** [hashicorp/terraform-provider-azurerm#24831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.91.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_named_value

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_named_value" "example" {
  name                = "example-apimg"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  display_name        = "ExampleProperty"
  value               = "Example Value"
}
```

### Debug Output/Panic Output

```shell
│ Error: "display_name" may only contain alphanumeric characters, periods, underscores and dashes
│
│   with azurerm_api_management_named_value.example,
│   on mian.tf line 5, in resource "azurerm_api_management_named_value" "example":
│    5:   display_name        = "ExampleProperty"
│
```

### Expected Behaviour

No validation error is returned, the named value is deployed successfully.

### Actual Behaviour

Validation error is raised, the named value is not deployed successfully.

### Steps to Reproduce

- terraform apply

### Important Factoids

Issue only started with v3.91.0 of the provider. Appears to be introduced by #24749

**Comment by rikribbers** [comment]
Same issue here; I did reproduce with version 3.90.0 and terraform plan was succesful so it was introduced in the latest release (3.91.0)

**Comment by Lars-Kolsaker** [comment]
Same issue here. Version 3.90 is working, 3.91 fails

**Comment by alexwiese** [comment]
I’ve raised PR #24832 to fix this

**Comment by rdhaundiyalf5** [comment]
i have started getting same error in my application . what version am i supposed to change, it was working perfectly fine till day before yesterday

**Comment by alexwiese** [comment]
@rdhaundiyalf5 you can pin the version of azurerm to 3.90.0

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.90.0"
    }
  }
}

The issue should be fixed in v3.92.0 once it’s released.

**Comment by rdhaundiyalf5** [comment]
Thanks @alexwiese , i did that already and it started working. Earlier I was trying with v3.92.0 as I thought it was released

**Comment by hoaza** [comment]
We use a pipeline that always uses the latest version of terraform and azurerm. Does anyone have any ideas other than limiting the display_name to one character and waiting for the new version to be distributed?

**Comment by sushmitapandey** [comment]
My code also picks the latest terraform version and I am still getting the same error. Can anyone please help me with the ETA. when is it going to be fixed and what version should I use? I have already tried 3.90 and 3.91 but no luck.

**Comment by jussiheinonen** [comment]
Ran into same issue with version 3.91.0 provider. Downgraded provider version to 3.90.0 and plan/apply is working fine again.
Be explicit with the version statement `version = "3.90.0"` not `version = ">= 3.90.0"` to prevent Terrraform using the cached 3.91.0 provider from the previous run.
