### ISSUE TITLE
azurerm_storage_sync_server_endpoint - Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by brentisaacs** [hashicorp/terraform-provider-azurerm#26014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.104.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_sync_server_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_storage_sync_server_endpoint" "sync-server-endpoint" {
  count                      = 1
  name                       = "my-ssse"
  storage_sync_group_id      = "/subscriptions/.../resourceGroups/my-main-rg/providers/microsoft.storagesync/storageSyncServices/my-storagesync-svc/syncGroups/my-ssg"
  registered_server_id       = "/subscriptions/.../resourceGroups/my-main-rg/providers/Microsoft.StorageSync/storageSyncServices/my-storagesync-svc/registeredServers/..."
  server_local_path          = "D:\mypath"
  cloud_tiering_enabled      = true
}
```

### Debug Output/Panic Output

```shell
Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.my_az_filesync["myfileshare"].azurerm_storage_sync_server_endpoint.sync-server-endpoint[0],
│ provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced
│ an unexpected new value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
##[error]Terraform command 'apply' failed with exit code '1'.
```

### Expected Behaviour

Successful terraform provisioning and state file update

### Actual Behaviour

Terraform applied the changes, but showed as a failure and did not update the state file

### Steps to Reproduce

1. terraform apply

**Comment by bruceharrison1984** [comment]
I believe this was fixed by this PR:
https://github.com/hashicorp/terraform-provider-azurerm/pull/26204

It should be available in the next release.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #26204. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
