### ISSUE TITLE
Provider crashes after modifying resource in Azure Portal

### ISSUE THREAD

**Issue by SamuelRochcongar** [hashicorp/terraform-provider-azurerm#27759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

tested with 1.9.5 and 1.7.5

### AzureRM Provider Version

tested with 4.6.0 and 4.5.0

### Affected Resource(s)/Data Source(s)

azurerm_data_protection_backup_vault

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "backup" {
  name     = upper("${var.prefix}-backup-tmp")
  location = var.location
  tags     = var.default_tags

}

resource "azurerm_data_protection_backup_vault" "sap_vm" {
  name                       = "sap-vault-vm-tmp"
  resource_group_name        = azurerm_resource_group.backup.name
  location                   = azurerm_resource_group.backup.location
  datastore_type             = "VaultStore"
  redundancy                 = "ZoneRedundant"
  retention_duration_in_days = 14 # Retention of backup when delete (soft delete)
  soft_delete                = "On"
  identity {
    type = "SystemAssigned"
  }
  tags = var.default_tags
}
```

### Debug Output/Panic Output

```shell
Acquiring state lock. This may take a few moments...
azurerm_resource_group.backup: Refreshing state... [id=/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx/resourceGroups/RG-CH-SAP-BACKUP]
azurerm_data_protection_backup_vault.sap_vm: Refreshing state... [id=/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx/resourceGroups/RG-CH-SAP-BACKUP/providers/Microsoft.DataProtection/backupVaults/sap-vault-vm]
azurerm_data_protection_backup_vault.sap_hana: Refreshing state... [id=/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx/resourceGroups/RG-CH-SAP-BACKUP/providers/Microsoft.DataProtection/backupVaults/sap-vault-hana]

Planning failed. Terraform encountered an error while generating this plan.


Error: Request cancelled

  with azurerm_data_protection_backup_vault.sap_vm,
  on main.tf line 10, in resource "azurerm_data_protection_backup_vault" "sap_vm":
  10: resource "azurerm_data_protection_backup_vault" "sap_vm" {

The plugin.(*GRPCProvider).ReadResource request was cancelled.
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-azurerm_v4.6.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58b08af]

goroutine 106 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/dataprotection.resourceDataProtectionBackupVaultRead(0xc002e30200, {0x70111e0?, 0xc001a27208?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/dataprotection/data_protection_backup_vault_resource.go:260 +0x6af
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x8858b18?, {0x8858b18?, 0xc002e19d10?}, 0xd?, {0x70111e0?, 0xc001a27208?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:783 +0x15f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc001132460, {0x8858b18, 0xc002e19d10}, 0xc00194bc70, {0x70111e0, 0xc001a27208})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x529
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000bc80a8, {0x8858b18?, 0xc002e19c50?}, 0xc002d74d00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x4aa
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0xc000e55c00, {0x8858b18?, 0xc002e19980?}, 0xc002d74d00)
	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0007fb720, {0x8858b18?, 0xc002e191a0?}, 0xc000f0b3b0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:783 +0x309
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x7d172e0, 0xc0007fb720}, {0x8858b18, 0xc002e191a0}, 0xc002cddf00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000159000, {0x8858b18, 0xc002e19110}, {0x8885520, 0xc0001e4600}, 0xc002de86c0, 0xc001586ed0, 0xdd30388, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000159000, {0x8885520, 0xc0001e4600}, 0xc002de86c0)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 22
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-azurerm_v4.6.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Expected Behaviour

The plan to work

### Actual Behaviour

The provider crashes 

### Steps to Reproduce

1. Deploy a `azurerm_data_protection_backup_vault` via Terraform 
2. Reach the Azure portal and change the Cross Subscription Restore setting from **Enable** to **Disable**
3. Run `terraform plan` again 

NB: The issue persist even if the parameter has been reverted to **Enable**
NB2 : I was trying to check if this parameter was handled by the provider because it doesn't appear in the doc. 

### Important Factoids

Running in Github CICD & on local computer - Same behavior

**Comment by sinbai** [comment]
Hi @SamuelRochcongar thanks for raising this issue. The issue should be fixed by this [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/27762), could  you please track it for further updates?

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #27762. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
