### ISSUE TITLE
Error:unexpected status 409 (409 Conflict) with error: VolumeReplicationMissingFor: Volume Replication was not found for volume:

### ISSUE THREAD

**Issue by mmanjunatha** [hashicorp/terraform-provider-azurerm#29112]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6

### AzureRM Provider Version

3.114.0

### Affected Resource(s)/Data Source(s)

azurerm_netapp_volume

### Terraform Configuration Files

```hcl
resource "azurerm_netapp_account" "netapp_account" {
  name                = "testaccount"
  resource_group_name = var.resource_group
  location            = var.azure_location

  dynamic identity {
    for_each = var.cmk_enabled || var.identity_login ? [1] : []
    content {
      type         = var.identity_type
      identity_ids = [
        var.user_assigned_identity_id
      ]
    }
  }

  tags    = var.tags
}

resource "azurerm_netapp_account_encryption" "netapp_encryption" {
  count                      = var.cmk_enabled ? 1 : 0
  netapp_account_id          = azurerm_netapp_account.netapp_account.id
  user_assigned_identity_id  = var.user_assigned_identity_id
  encryption_key             = var.key_id
}

# Creating netapp pool
resource "azurerm_netapp_pool" "netapp_pool" {
  name                = "testpool"
  account_name        = azurerm_netapp_account.netapp_account.name
  resource_group_name = var.resource_group
  location            = var.azure_location
  service_level       = "Premium"
  size_in_tb          = 4
  tags                = var.tags
}

# Creating the volumes

resource "azurerm_subnet" "netapp_volume_subnet" {
  count                = var.use_existing_vnet ? 0 : 1
  name                 = "test-netapp-subnet"
  resource_group_name  = var.resource_group
  virtual_network_name = var.vnet_name
  address_prefixes     = var.netapp_subnet_cidr

  delegation {
    name = "netapp"

    service_delegation {
      name    = "Microsoft.Netapp/volumes"
      actions = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    }
  }
}

resource "azurerm_netapp_volume" "netapp_volume1" {
  name                       = "testvol1"
  resource_group_name        = var.resource_group
  location                   = var.azure_location
  zone                       = "1"
  account_name               = azurerm_netapp_account.netapp_account.name
  pool_name                  = azurerm_netapp_pool.netapp_pool.name
  volume_path                = "volume1"
  service_level              = "Premium"
  subnet_id                  = var.use_existing_vnet ? var.existing_netapp_subnet_id : azurerm_subnet.netapp_volume_subnet[0].id
  protocols                  = ["NFSv4.1"]
  security_style             = "unix"
  storage_quota_in_gb        = 100
  snapshot_directory_visible = false

  export_policy_rule {
      rule_index          = 1
      root_access_enabled = true
      unix_read_write     = true
      allowed_clients     = var.bastion_subnet_cidr
      protocols_enabled   = ["NFSv4.1"]
    }

  tags                       = var.tags
}

resource "azurerm_netapp_volume" "netapp_volume2" {
  name                       = "testvol2"
  resource_group_name        = var.resource_group
  location                   = var.azure_location
  zone                       = "1"
  account_name               = azurerm_netapp_account.netapp_account.name
  pool_name                  = azurerm_netapp_pool.netapp_pool.name
  volume_path                = "volume2"
  service_level              = "Premium"
  subnet_id                  = var.use_existing_vnet ? var.existing_netapp_subnet_id : azurerm_subnet.netapp_volume_subnet[0].id
  protocols                  = ["NFSv4.1"]
  security_style             = "unix"
  storage_quota_in_gb        = 100
  snapshot_directory_visible = false

  export_policy_rule {
      rule_index          = 1
      root_access_enabled = true
      unix_read_write     = true
      allowed_clients     = var.bastion_subnet_cidr
      protocols_enabled   = ["NFSv4.1"]
    }

  tags                       = var.tags
}
```

### Debug Output/Panic Output

```shell
Error:unexpected status 409 (409 Conflict) with error: VolumeReplicationMissingFor: Volume Replication was not found for volume: '/subscriptions/<subscription_ID>/resourceGroups/<resource_group>/providers/Microsoft.NetApp/netAppAccounts/<netapp_account>/capacityPools/<natapp_pool>/volumes/<vol_name>'
```

### Expected Behaviour

It should destroy the volume without any issue.  It should not check for replication volume status as we have not abled the replication while applying

### Actual Behaviour

Error:unexpected status 409 (409 Conflict) with error: VolumeReplicationMissingFor: Volume Replication was not found for volume: '/subscriptions/<subscription_ID>/resourceGroups/<resource_group>/providers/Microsoft.NetApp/netAppAccounts/<netapp_account>/capacityPools/<natapp_pool>/volumes/<vol_name>'

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I didn't reproduce this issue. Could you double check if below tf config and repro steps are correct?

Repro steps:
```
1. Run tf apply
2. Run tf destroy
```

tf config:
```
provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }

    key_vault {
      purge_soft_delete_on_destroy       = false
      purge_soft_deleted_keys_on_destroy = false
    }

    netapp {
      prevent_volume_destruction             = false
      delete_backups_on_backup_vault_destroy = true
    }
  }
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-netapp-test06"
  location = "eastus"
}

resource "azurerm_user_assigned_identity" "test" {
  name                = "user-assigned-identity-test06"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

data "azurerm_client_config" "current" {
}

resource "azurerm_key_vault" "test" {
  name                            = "anfakvtest06"
  location                        = azurerm_resource_group.test.location
  resource_group_name             = azurerm_resource_group.test.name
  enabled_for_disk_encryption     = true
  enabled_for_deployment          = true
  enabled_for_template_deployment = true
  purge_protection_enabled        = true
  tenant_id                       = data.azurerm_client_config.current.tenant_id
  sku_name                        = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    certificate_permissions = []
    secret_permissions      = []
    storage_permissions     = []
    key_permissions = [
      "Get",
      "Create",
      "Delete",
      "WrapKey",
      "UnwrapKey",
      "GetRotationPolicy",
      "SetRotationPolicy",
    ]
  }

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = azurerm_user_assigned_identity.test.principal_id

    certificate_permissions = []
    secret_permissions      = []
    storage_permissions     = []
    key_permissions = [
      "Get",
      "Encrypt",
      "Decrypt"
    ]
  }
}

resource "azurerm_key_vault_key" "test" {
  name         = "anfenckeytest06"
  key_vault_id = azurerm_key_vault.test.id
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "azurerm_netapp_account" "test" {
  name                = "acctestnatest06"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  identity {
    type = "UserAssigned"
    identity_ids = [
      azurerm_user_assigned_identity.test.id
    ]
  }

  depends_on = [azurerm_key_vault_key.test]
}

resource "azurerm_netapp_account_encryption" "test" {
  netapp_account_id         = azurerm_netapp_account.test.id
  user_assigned_identity_id = azurerm_user_assigned_identity.test.id
  encryption_key            = azurerm_key_vault_key.test.versionless_id
}

resource "azurerm_netapp_pool" "test" {
  name                = "acctestnptest06"
  account_name        = azurerm_netapp_account.test.name
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  service_level       = "Premium"
  size_in_tb          = 4

  depends_on = [azurerm_netapp_account_encryption.test]
}

resource "azurerm_virtual_network" "test" {
  name                = "acctest-VirtualNetwork-test06"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.88.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "acctest-Subnet-test06"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.88.2.0/24"]

  delegation {
    name = "testdelegation"

    service_delegation {
      name    = "Microsoft.Netapp/volumes"
      actions = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    }
  }
}

resource "azurerm_netapp_volume" "netapp_volume1" {
  name                       = "testvol1"
  resource_group_name        = azurerm_resource_group.test.name
  location                   = azurerm_resource_group.test.location
  zone                       = "1"
  account_name               = azurerm_netapp_account.test.name
  pool_name                  = azurerm_netapp_pool.test.name
  volume_path                = "volume1"
  service_level              = "Premium"
  subnet_id                  = azurerm_subnet.test.id
  protocols                  = ["NFSv4.1"]
  security_style             = "unix"
  storage_quota_in_gb        = 100
  snapshot_directory_visible = false

  export_policy_rule {
    rule_index          = 1
    root_access_enabled = true
    unix_read_write     = true
    allowed_clients     = ["1.2.3.0/24"]
    protocols_enabled   = ["NFSv4.1"]
  }
}

resource "azurerm_netapp_volume" "netapp_volume2" {
  name                       = "testvol2"
  resource_group_name        = azurerm_resource_group.test.name
  location                   = azurerm_resource_group.test.location
  zone                       = "1"
  account_name               = azurerm_netapp_account.test.name
  pool_name                  = azurerm_netapp_pool.test.name
  volume_path                = "volume2"
  service_level              = "Premium"
  subnet_id                  = azurerm_subnet.test.id
  protocols                  = ["NFSv4.1"]
  security_style             = "unix"
  storage_quota_in_gb        = 100
  snapshot_directory_visible = false

  export_policy_rule {
    rule_index          = 1
    root_access_enabled = true
    unix_read_write     = true
    allowed_clients     = ["1.2.3.0/24"]
    protocols_enabled   = ["NFSv4.1"]
  }
}
```

**Comment by paulomarquesc** [comment]
This is fixed by PR #29382

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #29382. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
