### ISSUE TITLE
app_settings block on azurerm_windows_function_app is mark as 'sensitive'

### ISSUE THREAD

**Issue by eliasmartinez93** [hashicorp/terraform-provider-azurerm#29718]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.2

### AzureRM Provider Version

4.29.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "windowsfunctionappsa"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_service_plan" "example" {
  name                = "example-app-service-plan"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Windows"
  sku_name            = "Y1"
}

resource "azurerm_windows_function_app" "example" {
  name                = "example-windows-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  app_settings = {
     "MyCustomSetting" = "MyCustomSettingValue"
  }

  site_config {}
}
```

### Debug Output/Panic Output

```shell
(not really needed)
```

### Expected Behaviour

As it happens on version `4.25.0` this would be the expected behaviour:

```
# module.my_module.azurerm_windows_function_app.my_function will be updated in-place
    ~ resource "azurerm_windows_function_app" "my_function" {
        ~ app_settings                                   = {
            - "MyNewAppSetting"                 = "NewValue" -> null
```

### Actual Behaviour

```
# module.my_module.azurerm_windows_function_app.my_function will be updated in-place
    ~ resource "azurerm_windows_function_app" "my_function" {
        ~ app_settings                                   = (sensitive value)
```

### Steps to Reproduce

- `terraform plan`
- `terraform apply`
- Go to the Azure Portal and manually add a new record on the AppSettings.
- Re-execute the `terraform plan`

### References

This seems to be generated on this PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/28689. The issue was originated when we migrated from `4.25.0` to `4.29.0` and this was released on `4.26.0`: https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v4.26.0

It seems to be applied to all Windows resources. Anyways this change should be rollback for all resources IMO It's quite risky not to see what is going to be modified, if you have any sensitive variables you should declare them as sensitive or use the key vault.

**Comment by xiaxyi** [comment]
Thanks @eliasmartinez93 for raising this issue, let me take a look and update once I find something.

**Comment by xiaxyi** [comment]
@eliasmartinez93  This was a mistake introduced by the PR that you've mentioned. That PR was meant to change the static web app but somehow ended up changing the windows function app.

The revert was made by the author in the pr https://github.com/hashicorp/terraform-provider-azurerm/pull/29358. The issue should be fixed once the revert PR gets merged.

**Comment by juanantoniofornericc** [comment]
According to https://github.com/hashicorp/terraform-provider-azurerm/issues/29834 this issue should have been fixed in azurerm 4.33.0 but I am using that last version and I am still getting
   ~ resource "azurerm_windows_function_app" "function_app_windows" {
      ~ app_settings                                   = (sensitive value)

**Comment by sreallymatt** [comment]
Hi @juanantoniofornericc, could you confirm the active provider version using `terraform -version`?

If you've previously applied changes where this field was marked sensitive, you should see a warning that the `app_settings` field will no longer be marked as sensitive after applying the change, after that the changes should be visible in plain text again.

e.g. from a test I just ran, created with v4.32.0, changed version to v4.33.0 and ran `terraform init -upgrade`, then `terraform apply`

```
Terraform will perform the following actions:

  # azurerm_windows_function_app.test will be updated in-place
  ~ resource "azurerm_windows_function_app" "test" {
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change. The value is unchanged.
      ~ app_settings                                   = (sensitive value)

```

**Comment by juanantoniofornericc** [comment]
Hi, thanks for replying, I am using terraform 1.12.2 x64, azurerm v4.33.0 and I do not get same warning as you:

```hcl
Terraform will perform the following actions:

# module.caf.module.function_apps_windows["xxxx"].azurerm_windows_function_app.function_app_windows will be updated in-place
  ~ resource "azurerm_windows_function_app" "function_app_windows" {
      ~ app_settings                                   = (sensitive value)

**Comment by eliasmartinez93** [comment]
The issue was solved for me. I added an Environment Variable to one of my functions and ran the plan. It showed me the changes about to be done (instead of sensitive value).

**Comment by sreallymatt** [comment]
Hi @juanantoniofornericc, I'm unable to reproduce your issue. Is it possible one of the modules you are using is marking a variable or other config used by `app_settings` as sensitive?

If you're still running into this, please open a separate issue with a minimal Terraform configuration that reproduces the issue.
