### ISSUE TITLE
While using create_mode = "Update" value to upgrade the version for Postgresql flexible server its replacing the values

### ISSUE THREAD

**Issue by zameer712** [hashicorp/terraform-provider-azurerm#30949]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

data "azurerm_client_config" "current" {}

resource "azurerm_postgresql_flexible_server" "postgress_azurerm_module_felxi" {
  name                          = var.name
  location                      = var.location
  resource_group_name           = var.resource_group_name
  sku_name                      = var.sku_name
  storage_mb                    = var.storage_mb
  storage_tier                  = var.storage_tier
  backup_retention_days         = var.backup_retention_days
  geo_redundant_backup_enabled  = var.geo_redundant_backup_enabled
  administrator_login           = var.administrator_login
  administrator_password        = var.administrator_password
  version                       = var.dbversion
  tags                          = var.tags
  create_mode                   = var.create_mode
  zone                          = var.zone
  auto_grow_enabled             = var.auto_grow_enabled
  public_network_access_enabled = var.public_network_access_enabled

  dynamic "high_availability" {
    for_each = var.high_availability
    content {
      mode                      = high_availability.value["mode"]
      standby_availability_zone = high_availability.value["standby_availability_zone"]
    }
  }

  lifecycle {
    ignore_changes = [
      zone
    ]
  }

  authentication {
    active_directory_auth_enabled = true
    tenant_id                     = data.azurerm_client_config.current.tenant_id
  }
}

resource "azurerm_postgresql_flexible_server_database" "hosting" {
  name      = var.dbname
  server_id = var.server_id
  charset   = var.charset
  collation = var.collation
}

### Terraform Version

1.0.0

### AzureRM Provider Version

3.116.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}
resource "azurerm_postgresql_flexible_server" "postgresql-server" {
  name                         = var.postgres-server
  resource_group_name          = var.resource_group
  location                     = var.location
  version                      = var.dbversion
  delegated_subnet_id          = var.subnet_id
  private_dns_zone_id          = var.private_dns_zone_id
  administrator_login          = var.administrator_login
  administrator_password       = var.administrator_login_password
  backup_retention_days        = var.backup_retention_days
  geo_redundant_backup_enabled = var.geo_redundant_backup_enabled
  storage_mb                   = var.storage_mb
  create_mode                  = var.create_mode
  sku_name                     = var.sku_name
  auto_grow_enabled            = var.auto_grow_enabled
  zone                         = var.zone
  dynamic "high_availability" {
    for_each = var.enable_highavailability ? toset([1]) : toset([])
    content {
      mode = "ZoneRedundant"
    }
  }
  lifecycle {
    ignore_changes = [zone, high_availability.0.standby_availability_zone,create_mode]
  }
  authentication {
    active_directory_auth_enabled = true
    tenant_id                     = data.azurerm_client_config.current.tenant_id
  }
  tags = var.custom_tags
}
```

### Debug Output/Panic Output

```shell
# module.postgresflex.azurerm_postgresql_flexible_server.postgresql-server must be replaced
-/+ resource "azurerm_postgresql_flexible_server" "postgresql-server" {
      + create_mode                   = "Update" # forces replacement
      ~ fqdn                          = "flexserver.postgres.database.azure.com" -> (known after apply)
      ~ id                            = "/subscriptions/***/resourceGroups/naas-pp-data/providers/Microsoft.DBforPostgreSQL/flexibleServers/flexserver" -> (known after apply)
        name                          = "flexserver"
      + private_dns_zone_id           = (known after apply)
      ~ storage_tier                  = "P10" -> (known after apply)
  
        }
        # (14 unchanged attributes hidden)

      ~ authentication {
          ~ active_directory_auth_enabled = false -> true
          + tenant_id                     = "***"
            # (1 unchanged attribute hidden)
        }
    }

  # module.postgresflex.azurerm_postgresql_flexible_server_configuration.query-capture-param must be replaced
-/+ resource "azurerm_postgresql_flexible_server_configuration" "query-capture-param" {
      ~ id        = "/subscriptions/***/resourceGroups/data/providers/Microsoft.DBforPostgreSQL/flexibleServers/flexserver/configurations/pg_qs.query_capture_mode" -> (known after apply)
        name      = "pg_qs.query_capture_mode"
      ~ server_id = "/subscriptions/***/resourceGroups/" -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }
```

### Actual Behaviour

  # module.postgresflex.azurerm_postgresql_flexible_server.postgresql-server must be replaced
-/+ resource "azurerm_postgresql_flexible_server" "postgresql-server" {
      + create_mode                   = "Update" # forces replacement
      ~ fqdn                          = "flexserver.postgres.database.azure.com" -> (known after apply)
      ~ id                            = "/subscriptions/***/resourceGroups/naas-pp-data/providers/Microsoft.DBforPostgreSQL/flexibleServers/flexserver" -> (known after apply)
        name                          = "flexserver"
      + private_dns_zone_id           = (known after apply)
      ~ storage_tier                  = "P10" -> (known after apply)
  
        }
        # (14 unchanged attributes hidden)

      ~ authentication {
          ~ active_directory_auth_enabled = false -> true
          + tenant_id                     = "***"
            # (1 unchanged attribute hidden)
        }
    }

  # module.postgresflex.azurerm_postgresql_flexible_server_configuration.query-capture-param must be replaced
-/+ resource "azurerm_postgresql_flexible_server_configuration" "query-capture-param" {
      ~ id        = "/subscriptions/***/resourceGroups/data/providers/Microsoft.DBforPostgreSQL/flexibleServers/flexserver/configurations/pg_qs.query_capture_mode" -> (known after apply)
        name      = "pg_qs.query_capture_mode"
      ~ server_id = "/subscriptions/***/resourceGroups/" -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Suggest upgrading TF azurerm provider to latest version since it has been resolved in the latest version.

<img width="722" height="457" alt="Image" src="https://github.com/user-attachments/assets/d32f8575-7d77-4ec0-a3e9-fd3d26b1024e" />

**Comment by zameer712** [comment]
@neil-yechenwei whats the version name to be used please do let me know

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as noted by @neil-yechenwei, as of his comment version 4.50.0 was the most recent, so please try upgrading. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the recent version (~4.x) in which you are still experiencing this issue, thanks!
