### ISSUE TITLE
azurerm_mssql_database always shows a change of license_type even if no change was made

### ISSUE THREAD

**Issue by luxiconn** [hashicorp/terraform-provider-azurerm#8346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Provider Version: 2.20.0
* Terraform 0.12.26

### Affected Resource(s)

* `azurerm_mssql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "sql_db" {
  name         = sql-db"
  server_id    = azurerm_mssql_server.app_sql_server.id
  collation    = "SQL_Latin1_General_CP1_CI_AS"
  license_type = "LicenseIncluded"
  max_size_gb  = 2
  sku_name     ="Basic"

  extended_auditing_policy {
    storage_endpoint                        = azurerm_storage_account.sql_audit.primary_blob_endpoint
    storage_account_access_key              = azurerm_storage_account.sql_audit.primary_access_key
    storage_account_access_key_is_secondary = true
    retention_in_days                       = 6
  }
}
```

### Expected Behavior

If I don't change anything in the resource terraform should now show the state different than what is deployed

### Actual Behavior

Every time we run `terraform plan` it acts like there is a change in the license type even though no change was made.

```hcl
resource "azurerm_mssql_database" "camunda_sql_db" {
        auto_pause_delay_in_minutes = 0
        collation                   = "SQL_Latin1_General_CP1_CI_AS"
        id                          = ""
      + license_type                = "LicenseIncluded"
        max_size_gb                 = 2
        min_capacity                = 0
        name                        = ""
        read_replica_count          = 0
        read_scale                  = false
        server_id                   = ""
        sku_name                    = "Basic"
        zone_redundant              = false

        threat_detection_policy {
            disabled_alerts      = []
            email_account_admins = "Disabled"
            email_addresses      = []
            retention_days       = 0
            state                = "Disabled"
            use_server_default   = "Disabled"
        }
    }
}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked, seems api doesn't return the value of license type. So I submit a [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8368) to fix this issue.

**Comment by NicolasSeiler** [comment]
@neil-yechenwei Apparently the linked issue is now resolved.

**Comment by vperaltac** [comment]
Any update on this? The issue raised in Azure was fixed months ago.

**Comment by dleborgne** [comment]
For what it worths, here is how I workaround this bug :

```
resource "azurerm_mssql_database" "this" {
  // [...]

  lifecycle {
    ignore_changes = [
      license_type
    ]
  }
}
```

**Comment by thllxb** [comment]
> Thanks for opening this issue. After checked, seems api doesn't return the value of license type. So I raised an issue on [Azure/azure-rest-api-specs#10715](https://github.com/Azure/azure-rest-api-specs/issues/10715).

The LicenseType property does get returned if the database was created using the latest api version.

**Comment by gerardwolf** [comment]
Any update on this? Still an issue in the 3.7.0 version of the azurerm provider.

**Comment by fcatacut** [comment]
I'm not running into this issue in AzureRM 3.11.

```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.11.0
```

Looking at Azure Portal, I believe that `license_type` only applies to vCore-based purchasing models (e.g. where `sku_name` is `GP_Gen*`, `BC_*`, etc.). Any attempt to set it for any other SKU appears to be ignored by the API.

Note: It looks as if Azure Portal is incorrectly displaying the specified license type. `LicenseIncluded` is displayed as _No_ whereas `BasePrice` is displayed as _Yes_. I confirmed the correct setting is applied using AZ CLI: https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-show.

**Comment by jaredbrogan** [comment]
Seeing this issue as well. Still happening on provider version `3.24.0`.

**Comment by damiensawyer** [comment]
Come on Hashicorp. 2 Years? Doesn't inspire confidence to start a new project with Terraform.

**Comment by vanmash** [comment]
Can someone remove "upstream-microsoft" tag, as it seems to be solved already

Perhaps @ArcturusZhang or @tombuildsstuff

**Comment by katbyte** [comment]
closing as @jaredbrogan as confirmed its been fixed
