### ISSUE TITLE
CosmosDB account modification fails on the policy

### ISSUE THREAD

**Issue by PavelSlepushkin** [hashicorp/terraform-provider-azurerm#9916]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform v0.12.28
azurerm provider  2.37
### Affected Resource(s)

* resource "azurerm_cosmosdb_account" "cosmosdb-account"
* 

### Terraform Configuration Files

```hcl
locals {
  resourceGroupName   = "testCMKrg"
  keyVaultName        = "testCMKkv321"
  location            = "northeurope"
  cosmosdbAccountName = "testcmkcosmosdb"
}

data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "key-vault" {
  name                     = local.keyVaultName
  location                 = local.location
  resource_group_name      = local.resourceGroupName
  tenant_id                = data.azurerm_client_config.current.tenant_id
  sku_name                 = "standard"
  soft_delete_enabled      = true
  purge_protection_enabled = true
  network_acls {
    bypass         = "AzureServices"
    default_action = "Allow"
  }

}

resource "azurerm_key_vault_access_policy" "cosmos-db" {
  key_vault_id = azurerm_key_vault.key-vault.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  #  https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-cmk
  #  not using azuread provider, using constant id for "Azure Cosmos DB" service principal
  object_id       = "28abcb86-816d-4a68-af63-894cf9e82f3f"
  key_permissions = ["get", "unwrapkey", "wrapkey"]
}

resource "azurerm_key_vault_access_policy" "client" {
  key_vault_id    = azurerm_key_vault.key-vault.id
  tenant_id       = data.azurerm_client_config.current.tenant_id
  object_id       = data.azurerm_client_config.current.object_id
  key_permissions = ["get", "create", "delete", "list", "restore", "recover", "unwrapkey", "wrapkey", "purge", "encrypt", "decrypt", "sign", "verify"]
}

resource "azurerm_key_vault_key" "kv-key" {
  name         = "keyforCosmosDB"
  key_vault_id = azurerm_key_vault.key-vault.id
  key_type     = "RSA"
  key_size     = 4096
  key_opts     = ["decrypt", "encrypt", "sign", "unwrapKey", "verify", "wrapKey"]
  depends_on = [
    azurerm_key_vault_access_policy.client,
    azurerm_key_vault_access_policy.cosmos-db
  ]
}


resource "azurerm_cosmosdb_account" "cosmosdb-account" {
  name                      = local.cosmosdbAccountName
  location                  = local.location
  resource_group_name       = local.resourceGroupName
  offer_type                = "Standard"
  enable_automatic_failover = true
  key_vault_key_id          = azurerm_key_vault_key.kv-key.id
  #  tags                      = { test = "test" }
  consistency_policy {
    consistency_level = "Session"
  }
  geo_location {
    location          = local.location
    failover_priority = 0
  }
}
```

### Expected Behaviour

Modification of a resource according to code changes

### Actual Behaviour

403 response from Azure API with policy error

### Steps to Reproduce

1. Create resource group named testCMKrg (name can be changed in TF configuration)
2. Create policy from attached file and assign it to created group (to reduce blast radius) (The source of the policy is https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Cosmos%20DB/Cosmos_CMK_Deny.json , defaultValue for an effect changed from "audit" to "deny")
[Cosmos_CMD_Deny.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/5709986/Cosmos_CMD_Deny.zip)
3. Create all resources required for CosmosDB account with Customer Managed Keys (code in configuration files) (terraform apply)
4. Modify code for CosmosDB account (for example - uncomment tags =.. string)
5. terraform apply will fail on the policy

Expected behaviour - apply should work.
My guess - the reason for it  - azure provider uses CreateOrUpdate method ((https://docs.microsoft.com/en-us/rest/api/cosmos-db-resource-provider/2020-04-01/databaseaccounts/createorupdate) from REST API instead of Update
( (https://docs.microsoft.com/en-us/rest/api/cosmos-db-resource-provider/2020-04-01/databaseaccounts/update)

Probably here (https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/cosmos/cosmosdb_account_resource.go#L518 ), but maybe in some other places as well.

**The fix will be:** 
to use Update method for an existing CosmosDB account and CreateOrUpdate for creation of account.
This is correct from REST point of view (PATCH method for updating resource, PUT for creating), it will also fix this and other potential policy issues. 
It can be tested on the same account with curl calls:
CreateUpdate call:
curl -X PUT -H "Authorization: Bearer $token" -H "Content-Type:application/json" -H "Accept:application/json" https://management.azure.com/subscriptions/${subscriptionID}/resourceGroups/testCMKrg/providers/Microsoft.DocumentDB/databaseAccounts/testcmkcosmosdb?api-version=2020-04-01 -d '{"tags":{"test":"test"}}' -v

fails with 403 and errors from policies
 
Update call for the same:
curl -X PATCH -H "Authorization: Bearer $token" -H "Content-Type:application/json" -H "Accept:application/json" https://management.azure.com/subscriptions/${subscriptionID}/resourceGroups/testCMKrg/providers/Microsoft.DocumentDB/databaseAccounts/testcmkcosmosdb?api-version=2020-04-01 -d '{"tags":{"test":"test"}}' -v

works and updates the tags

### References

* #0000

**Comment by dkuzmenok** [comment]
@PavelSlepushkin @tombuildsstuff 
I have investigated this issue. And was able to reproduce the issue.
It was fixed in v2.42.0 by this fix: [#9966](https://github.com/hashicorp/terraform-provider-azurerm/pull/9966)
Also working properly in latest versions.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #9966. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
